config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'beers#index'

  resources :beers

end

app/models/beer.rb
# File name has to be the Singular version of name of the db table

class Beer < ActiveRecord::Base



end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
before_action :set_beer, only: [:show, :edit, :update, :destroy]


	# List all of the beers
	def index
		@beers = Beer.all
	end

	# Show data for one beer
	def show

	end

	# Displays form for creating a new beer
	def new
		@beer = Beer.new
	end

	# Processes data form the new beer form and creates a beer
	def create
		@beer = Beer.new(beer_params)

		respond_to do |format|
	      if @beer.save
	        format.html { redirect_to beers_url, notice: 'A new beer was successfully created.' }
	        format.json { render :show, status: :created, location: @beer }
	      else
	        format.html { render :new }
	        format.json { render json: @beer.errors, status: :unprocessable_entity }
	      end
	    end
	end

	# Displays form for editing an existing beer
	def edit 

	end

	# Processes data form the edit beer form and updates a beer
	def update
		respond_to do |format|
	      if @beer.update(beer_params)
	        format.html { redirect_to beers_url, notice: 'That beer has successfully been updated.' }
	        format.json { render :show, status: :ok, location: @beer }
	      else
	        format.html { render :edit }
	        format.json { render json: @beer.errors, status: :unprocessable_entity }
	      end
    	end
	end

	# Deletes the beer
	def destroy
		@beer.destroy
		    respond_to do |format|
		      format.html { redirect_to beers_url, notice: 'That beer was successfully destroyed.' }
		      format.json { head :no_content }
		    end
	end

	private
  	def set_beer
      @beer = Beer.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :brewer, :beer_type, :abv)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brewer %><br>
    <%= f.text_field :brewer %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :beer_type %><br>
    <%= f.text_field :beer_type %>
  </div>
  <div class="field">
    <%= f.label :abv %><br>
    <%= f.text_field :abv %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<p id="notice"><%= notice %></p>
<h1>All Brewz</h1>

<h3><%= link_to 'Post a New Beer!', new_beer_path %>
<%= link_to 'Users', users_path %></h3>


<% @beers.each do |beer| %>
	<p>
	<strong>Name: </strong><%= beer.name %>
	<strong>Brewer: </strong><%= beer.brewer %>
	<strong>Type: </strong><%= beer.beer_type %>
	<strong>ABV: </strong><%= beer.abv %>
	<strong><%= link_to 'Show', beer %></strong>
    <strong><%= link_to 'Edit', edit_beer_path(beer) %></strong>
    <strong><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></strong>

	</p>

	<% end %>

	

app/views/beers/new.html.erb
 <h1>New Beer</h1>
 
 <%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Brewer:</strong>
  <%= @beer.brewer %>
</p>

<p>
  <strong>Type:</strong>
  <%= @beer.beer_type %>
</p>

<p>
  <strong>ABV %:</strong>
  <%= @beer.abv %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Brewz</h1>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3><%= link_to 'Create New User', new_user_path %>
<%= link_to 'Post a New Beer', new_beer_path %>
<%= link_to 'List of Beers', beers_path %></h3>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>